### ISSUE TITLE
Oil smelter AI buying and selling pitch constantly bug.

### ISSUE THREAD

**Issue by PitchNeeded** [Sh0wdown/UnofficialCrusaderPatch#304] opened 2019-04-07 10:26 UTC
Now AICE is able to change the AIs troops, and we shall be experimenting more changing AI troops, the bug that happens if an oil smelter is added to an AI that doesn't usually have one should be fixed I think. The AI keeps buying and selling 4 pitch constantly, losing gold in the process.

**Comment by Lolasik011** [comment] 2019-04-07 10:29
@PitchNeeded Already test AICE?

**Comment by PitchNeeded** [comment] 2019-04-07 11:19
@Lolasik011 No not yet! I don't have the working version, only the creators do.

**Comment by Truetobi91** [comment] 2019-04-07 11:51
I wouldn't call that a bug because it's an intended behaviour. You already can adress that in the AICE under "market" by unchecking the option to sell **Pitch**. You'd then have to test if the change is already enough or if you need another option about how much pitch can be stored (min/max) which is not available yet. 

I think there are plenty of options yet to come for the full version of AICE but I already though about opening an faq issue for the tool. 

Is that a bug? I mean you could uncheck the option to sell "pitch" in "market" and then see if the "bug" is actually a bug.

**Comment by ByBurton** [comment] 2019-04-07 12:25
Hello, creator of the AICE here.
That is not a bug, but intended behavior. It seems you tried to give an AI Lord, that normally does not use pitch, an oil smelter.
The AI has pitch as sell item configured, which means it will sell pitch if it has any asap.
But having an oil smelter will force the AI to always have pitch on stock. 
Both routines set in, and the AI Lord will keep buying & selling.
You have to set the variable for Max Other, which includes stuff like flour, iron, pitch.

**Comment by Truetobi91** [comment] 2019-04-07 12:36
You did that with Pig correct?

**Comment by DarkThief-Darek** [comment] 2019-04-07 13:34
@ByBurton  Just for understanding: The "maxOther" variable can only set a max for multiple goods like flour, iron, pitch? Is there not a variable where you can define how many pitch they need to keep in stock and don't keep iron and flour in the stock?

**Comment by PitchNeeded** [comment] 2019-04-07 14:11
> You did that with Pig correct?

No I was testing Lord Woolsack's castles using Phillip of course! :D 

@ByBurton The problem with the oil smelter buying and selling seems easy to fix then! :D

**Comment by ByBurton** [comment] 2019-04-07 14:24
@DarkThief-Darek No, there is not. Sorry.

**Comment by Sh0wdown** [comment] 2019-04-07 19:30
As others have already commented it should indeed be fixed by changing the SellResource parameters of the AICs.

**Closed by Sh0wdown** 2019-04-07 19:30 UTC
