### ISSUE TITLE
AI castles not working on multiplayer

### ISSUE THREAD

**Issue by tprj29** [Sh0wdown/UnofficialCrusaderPatch#475] opened 2019-11-26 16:29 UTC
First of all I would like to state that I really love this patch. I have used it a couple of times for single player and everything seems to be running fine there. But now I am trying to play with my friends and there is where the problems start. In multiplayer with the patch installed the AI lords are broken. 

### We tried 2 things. 
1. I installed the patch and set AIV to @Evrey's improved castles and my friends installed the patch and kept every setting as suggested by the patch installer by default (@Evrey's fixed castles).
   - AI lords are not building anything. 
   - _**This is kinda expected behavior but I thought it might still be good to include. Since this might give some more insight in what is happening.**_
2. We all installed the patch and kept every setting as suggested by the patch installer by default (@Evrey's fixed castles).
   - AI lords are building castles build there attacks seem broken. They don't use their catapults etc. in the way they normally do. They just run them towards are castle walls until they got destroyed by our rangers. The AI lords never started to shoot them at our walls. 
3. We all installed the patch and set AIV to @Evrey's improved castles.
   - AI lords send small attacks with only ground troops (so no engineers) but they didn't every send a taunt message and didn't use engineers in there "attacks".

### Questions
1. Is online supported?
2. If online isn't supported is it every going to be?

Thanks in advance.

**Comment by J-T-de** [comment] 2019-11-26 18:14
Online is supported. It should be working if
- all of you use the same base version of Crusader (e.g. 1.3.1 or 1.4.1)
- all of you use the same version of the UCP (current one is 2.13)
- all of you use the same UCP settings
The first two points can be checked in the main menu on the lower left corner. The last point can be checked either manually or you guys can share the ucp.cfg. Usually, the problem is due to the last point. Can you check again carefully?

**Comment by tprj29** [comment] 2019-11-26 18:32
Thanks for your quick response. I'll try to validate asap and will get back to you with the answer.

**Comment by GRhin** [comment] 2019-11-27 01:19
I play online with ais all the time on my stream, I have some YouTube videos on it if you want to confirm. One way to ensure you and your friends have the same setup is to share the .cfg file that gets generated in the patched install location. There are a couple bugs with this method.
- ai lords channel, 5th option, rate of attacking troops, if you use the second sub option to increase troops by a multiplier, you need to double check thus option if your friends have a different region computer settings (one person in say germany with a comma as decimal point, others having a period)
- aic settings are not transferred.

**Comment by tprj29** [comment] 2019-11-27 09:20
Okay, thanks for the reply. I tested this with one of my friend last night with fixed castles enabled. It seems to be working correctly. Maybe it was a problem with the different  ucp.cfg somehow that we had overlooked. Anyway will do some more testing shortly to validate if it was just a wrong setup on my part. I 'll keep you posted!

**Closed** 2019-11-27 09:20 UTC
