### ISSUE TITLE
Stronghold Crusader Extreme UnofficialPatch too

### ISSUE THREAD

**Issue by GGM90** [Sh0wdown/UnofficialCrusaderPatch#210] opened 2019-01-10 07:05 UTC
I've installed it the latest patch for crusader from this page, but i realize there only works for the normal Crusader and not for the Extreme version. It would be awesome if the patch had the compatibility to this version too, like the bugs fixes, improvements, change color, etc. Thanks you guys!

**Comment by Sh0wdown** [comment] 2019-01-10 10:02
If you rename "Stronghold Crusader Extreme.exe" temporarily to "Stronghold Crusader.exe" before applying the patch, you should be able to get the changes for extreme too. Some of them might not work though (total troop limit f.e.), so you have to test a bit.

But yea, I should add an option to the setup to patch Extreme too.

**Comment by ByBurton** [comment] 2019-01-10 10:09
Haha, I actually forgot that there is an extreme version of Crusader,

**Comment by Heroesflorian** [comment] 2019-01-10 20:53
Hmm... I think this here is a duplicate of this older issue (which also shows another "use case" for SHC-E besides the "commonly known stuff" that isn't currently available in regular SHC) from November: https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/86

**Comment by GGM90** [comment] 2019-01-13 05:32
There's other improvement you should put in the next update. I realize, that when a AI enemie send you a video message, they appear with the same color as me, for example, if i put the patch with the yellow color for me, then in game, playing with AI, one of them is red now, right? Yep, but when the red one send me a message it will appear with the same colour as me in the video message, in this case, the yellow color. It's a minor issue, but i think it could be good if you fix it too :)

**Comment by PitchNeeded** [comment] 2019-01-17 09:44
Also some of the features of Stronghold Crusader Extreme that make it different to Stronghold Crusader could do with some patching too! Some changes I would like to see in Stronghold Crusader Extreme:

1. the first change I would really like to see is that some of the spawned units could be sent to the controlling AI's castle and used defensively by AIs, particularly archers, fire throwers, crossbowmen, slingers and Arabian archers

2. some spawned troops of the type the AI uses can be sent to the castle to make up the siege force.

3. slaves spawned will dig up moats

4. Reduce the effect of the rock volley a bit, its too strong I think! Also the gold amount you get with the gold ability is too much I think.

**Comment by ByBurton** [comment] 2019-01-17 10:09
The AI should be able to use those abilities. Why restrict it to human players only?

**Comment by Heroesflorian** [comment] 2019-01-20 15:46
It would certainly make SHC-E more demanding, but probably the skirmish trail will be completely impossible to complete then! :D 

Most missions there are balanced by the formula "AI gets tons of outposts, human gets abilities"... if now AI uses outposts more effectively, and gets abilitities as well on top of that, then human players wouldn't stand a chance probably - especially against multiple AI opponents.

**Comment by PitchNeeded** [comment] 2019-01-20 17:56
Well I don't know about abilities at the minute, but AIs in Stronghold Crusader Extreme should be modified to  use their outpost troops to defend as well as attack at least, I really don't like how the AI's outpost troops all just automatically attack, as it takes the personality of the AIs out of the game. Outpost troops, if they are the right types of troops for an AI, should join gathering siege forces in AI castles too.

**Comment by Sh0wdown** [comment] 2019-02-22 22:50
The patcher will also edit Extreme now in the upcoming version 2.10.

**Closed by Sh0wdown** 2019-02-22 22:50 UTC
Labels: enhancement
