### ISSUE TITLE
Ideas / Discussion towards AI wall defence

### ISSUE THREAD

**Issue by ByBurton** [Sh0wdown/UnofficialCrusaderPatch#248] opened 2019-03-04 08:24 UTC
Hi,
so the next version will probably have upgraded and working ai wall / tower manning.
This will open up a whole lot of options.
For example I tested around a bit yesterday or on Saturday, and gave the Wolf arabian archers, which makes the wolf able to light pitch. I also upped the amount of units he puts on the walls.

So, what are you ideas, wishes? Try to think about balance for AI vs AI matches as well, not only Player vs Ai.

My propositions:
Rat: Upgrade to about 90 to 120 wall defence, 110 to 140 total defence. But with a focus on spearmen, not archers. 1: 2 maybe. (results in 30 archers and 60 spearmen up to 40 archers and 80 spearmen)
Pig: Slightly up the amount of patrols and wall defence, and also recruit some macemen every 6th unit or smthg.
Sultan: Slightly more men, but also very few fire throwers and arab. archers (maybe?).
Caliph: Very few slingers.
Wolf: Up wall defence and patrols just a little bit. European archers, arabian archers, crossbowmen and pikemen in a 1:1:2:1 maybe.
Saladin / Wazir: A few more arabian archers, very few slingers (maybe?) and a few more patrols. For Wazir even more patrols.
Nazir: Add a few wall defence, and very few assassins to the wall defence.
Richard. A few more archers than vanilla, but also pikemen and swordmen for wall defence.
Emir: A few Arabian swordsmen as wall defence?
Abbot: I hate this guy. Give him more patrols for his economy. He is a hamster after all.

Edit:

Also could we have a list of units and their hex values? I tried to mess around and did not know any units besides archers, crossbowmen, spearmen and pikemen.
If so, I might be able to code a little programm that creates textfiles / scripts that you could read in.
How about that? (It would not look great, but it would work. Would do it in C#, Windows forms probably)

**Comment by brooklynzsmac** [comment] 2019-03-04 14:13
Every bot should man as many archers on towers as Snake does.

**Comment by Panbutt** [comment] 2019-03-04 15:03
Phillip def needs some work. Since he never trains archers specifically for defense. I don't think he should hire too many archers, maybe 3 or so per AIV Editor 'archer token'. Given his crazy amount of stables, I feel like he should train knights specifically for castle defense.

Sultan needs to retrain killed firethrowers. I'd love him to use wall archers but that would require AIV edits. Maybe have him train a set number (maybe 12 or so) archers specifically to stay in the keep?

**Comment by ByBurton** [comment] 2019-03-04 15:05
@Panbutt I disagree about Philipp's defense. He should have at most 2 units per aiv spot.
Instead he should have more knights, as you mentioned.
About Sultan and archers. If there are no aiv spots for them, then he will keep them on his ... keep.
Which would be kinda cool I guess.

**Comment by ByBurton** [comment] 2019-03-04 15:06
I am halfway done with creating a small tool to create scripts.
@Sh0wdown I kinda need your help for the last step. I need a list of hex - values for the unit types.

**Comment by ByBurton** [comment] 2019-03-04 19:03
The tool is in beta, and can be downloaded [on my google drive.](https://drive.google.com/file/d/15U1U9-bM_gijru_gSQ_DhimWxUYruHlL/view?usp=sharing)

It won't do anything yet though, Nere needs to actually use the files I create.
@Sh0wdown I will attach an example output file FYI.

[zipidi_zapidi_IT.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/2927831/zipidi_zapidi_IT.zip)

**Comment by Heroesflorian** [comment] 2019-03-04 19:54
**Some more suggestions:** 
- Saladin also sometimes struggles with replacing his fire throwers. 
- Abbot could use some (more?) monks for wall defense, and a little bit more archers (currently has 3 on some/most of his spots, and just 1-2 on a few others, when 10 spots are used... more even distribution with 3 on every spot would be nice!). Archer patrols he does use already (given enough bow production or patch-allowed bow purchases) in sufficient numbers I'd say. 
- Sheriff should use more crossbowmen - right now, he usually has only 1-2 crossbows per spot, which is a bit low; 2 crossbows on every spot would be the least one can expect from him! Probably even 3, given he is a rather strong AI and has quite large castles (distributing fire power over large area). 

**But, now, I've got some questions:** 

> Rat: Upgrade to about 90 to 120 wall defence, 110 to 140 total defence.

- So what exactly is "wall defense" and what is "total defense" / where's the difference? 
- Also, if you propose new values such as "90 to 120", it would be useful to know the current value as a baseline to compare with. 

> Pig: Slightly up the amount of patrols and wall defence

- If there is "patrols"... do those count towards the "total defense"? Are those the patrols that are sent out of the castle to protect workers? 
- What about raiding troops (e.g. Marshal's knights or Caliph's slaves) - can those be modified in terms of troop types or numbers as well now? How (if at all) do they factor in with the other values? 
- What about siege attack troops, can those be modified as well? 

> Nazir: Add a few wall defence, and very few assassins to the wall defence. 

- Afaik, Nizar currently uses 80 Arabian archers for his towers (wall defense?), which is about enough I'd say. Adding additional assassins might be neat, but additional archers (in case you also meant that, not sure) I do not think are necessary... with that many archers already there, I'd rather see him use some tower ballistae for long-ranged defense (yes, I know, that would be AIV not AI-character) than even more archers unable to defend against siege engines. 

> Wolf: Up wall defence and patrols just a little bit. European archers, arabian archers, crossbowmen and pikemen in a 1:1:2:1 maybe.

- So what would those pikemen do on the walls? Will they behave like Rat's spearmen, i.e. patrolling between all placed spots, or will they just stand in place on the individual spots? 
- Also, is it possible to explicitly specify one or the other type of behavior (guarding a spot vs patrols between spots)? 
(Depending on what is the answer to those two questions, I have more suggestions for melee troop usage on defense for some AI characters...)

**What I get (or think I get) so far is:** 
- There is some sort of "troop budget" for AI characters, that gets distributed among several troop types and the spots placed for them, according to some hardcoded / soon-configurable ratio. 
- It is possible to change those values, as well as what troop types the AI uses for manning their walls and towers (or the keep, if no corresponding slots are placed in an AIV, but that "fallback behaviour" is already present in vanilla Crusader, of course). 
- It seems to be possible to give entirely new troop types to an AI character (e.g. slingers to Caliph as you suggested above). 
- These are exciting times to witness! :D

**Comment by ByBurton** [comment] 2019-03-04 20:06
@Heroesflorian 
Let me post the answers here:

> So what exactly is "wall defense" and what is "total defense" / where's the difference?

Wall defence are the static troups used to protect the castle, NOT the economical buildings outside (woodcutters etc). Total defence is patrols + wall def.


> Also, if you propose new values such as "90 to 120", it would be useful to know the current value as a baseline to compare with.

Current value is 20 for wall def and 30 or something for total def.


>What about raiding troops (e.g. Marshal's knights or Caliph's slaves) - can those be modified in terms of troop types or numbers as well now? How (if at all) do they factor in with the other values?

No idea.

> What about siege attack troops, can those be modified as well?

No idea.

> In regards to Nazir: 

80 archers for his huge castles seems not enough, especially because those big towers aren't even half full most of the times.

> So what would those pikemen do on the walls? Will they behave like Rat's spearmen, i.e. patrolling between all placed spots, or will they just stand in place on the individual spots?

Nope, sadly not. except for very few AI lords (like the rat, pig) have patrols. They defend the lord and storm out, once the walls are breached. Pretty effective in a lot of cases.

> Also, is it possible to explicitly specify one or the other type of behavior (guarding a spot vs patrols between spots)?

No idea.

Let me try to sum it up again:
We have two values, wall defence, which means all static defences used to protect the ai village itself and total defence, which also includes patrols that protect the outside eco (e.g. Sultans army to protect his quarries, same for rat, or Saladins army of archers patrolling around).
Then recruiting defensive units, the army goes through a list of units to recruit (up to 8) and after the last one it loops around. It won't recruit crossbowmen if it does not have crossbows and leather armor though for example. So if we have 2 spots of archers, and 1 spot of spearmen (and the rest empty), then we have double the amount of archers as defence.

**Comment by Heroesflorian** [comment] 2019-03-04 20:28
> 80 archers for his huge castles seems not enough, especially because those big towers aren't even half full most of the times. 

Well, one thing to also consider: Nizar can have more than 5 archers stacked up on the small towers (80 archers / 10 spots = 8 archers per spot) as well. So sometimes one just doesn't see all of his archers. 
I also tried putting all 10 spots (as well as, in a second test, placing just 1 spot in total, there) on a gate house. This resulted in 80 archers on said gatehouse. Obviously, a small 5x5-gate (25) or larger 7x7-gate (49) has not enough tiles to properly show all 80 archers next to each other, and they stack on the same tiles once there are no more empty tiles left. 

Anyway, 80 Arabian archers (if Nizar has enough gold and tranquility to manage getting all of them in place) is quite a lot, actually. 
Compare that to e.g. Emir or Saladin - both of which can have some rather huge castles as well! 
They only use like (guessed) 20-40 Arabian archers. And no defensive fire ballistae either (with vanilla AIVs). 
(Yes, Emir (with weapon purchasing) can have a bunch of additional European archers, but still he doesn't get anywhere near Nizar's numbers. And Emir's oil engineers are AIV-specific and can be used by Nizar as well.) 

Now, don't get me wrong - I don't want to disadvantage Nizar compared to others, but I just really think the best way to buff Nizar is not necessarily "more archers", but other changes. Be it AIV-related ones (protective walls around towers, tower siege engines, oil pots, pitch ditches, more efficient castle layouts for shorter walking distances and more effective bread production, ...), or AI behaviour adjustments (some additional quarries or iron mines or whatnot, to get more gold from selling resources, additional siege engines or auxiliary ranged troops for Nizar's attacks, better assassin AI, improved assassin (and/or slave) harassment, ...). 

---

> Current value is 20 for wall def and 30 or something for total def. 

> We have two values, wall defence, which means all static defences used to protect the ai village itself and total defence, which also includes patrols that protect the outside eco (e.g. Sultans army to protect his quarries, same for rat, or Saladins army of archers patrolling around).

Sometimes the AI goes crazy, sending tons of units to guard quarries or other economy... I've seen the Rat guard a quarry with over 60 troops (both archers and spearmen) sometimes. Considering the fact `60 > 30`, I wonder how that behaviour can be explained... there must be either situations in which the AI **ignores the total def limit**, or additional values besides the currently known total / wall def.

**Comment by LordDerMoff** [comment] 2019-03-04 20:43
I agree with most of your points @ByBurton , but even as strongly i would like to see poor ratty a bit better off than now, i disagree on the amount of troops. Sure, Rat is a Lord nonetheless and should at least have a decent amount of bodyguards on its keep. I do feel sorry for the poor rat for being killed instantly by the other ais or by the human player, still it is a goddammed Rat and no character in the Stronghold Universe was ever made to be defeated by the Rat (not even poor Sultan must sleep the sleep of the ancients against the glorious forces of de Puce). So doubling - even trippling seems alright, but from 20 30 to 90 110 or even 120 140 seems way too much

**Comment by Panbutt** [comment] 2019-03-04 20:58
One minor thing I would suggest also: Snake never retrains his wall slingers. He actually only uses his starting slingers (much like phillip and his archers). I'd suggest 3 slingers per spot instead of the usual one and to also allow him to retrain slingers KIA.

Also for Pig, I actually am fond of the idea of him using few crossbowmen and just using craploads of macemen in compensation. He's pretty much a marauding bandit. He will position macemen on macemen tokens placed in AIVs, however only the first two. Anymore placed causes him to use those macemen to patrol those spots, which can be pretty handy for castle defense.

Sheriff ... Yeah. He needs an upgrade to the priority of defensive crossbowmen. Most games he'll only have 4-5 crossbowmen -total- defending his castle. He relies way too much on firethrowers who can be easily killed.

**Comment by ByBurton** [comment] 2019-03-04 20:59
@LordDerMoff The rat would still lose to every enemy with armored forces, e.g. the Sultan.
With my proposed defences (I take 100 wall def. and 120 total def. for now), the rat would have 6 7 spearmen and 33 archers on his walls, and 20 archers and spearmen mixed on his quarry.

**Comment by ByBurton** [comment] 2019-03-04 21:02
@Panbutt Firethrowers for Sultan, Slingers for the Snake. These things can easily be adjusted. We will just have to wait for @Sh0wdown to implement and release a version, which includes support for my tool, so you guys can have your wishes..

**Comment by Sh0wdown** [comment] 2019-03-04 23:53
> Abbot: I hate this guy. Give him more patrols for his economy. He is a hamster after all.  
Judging from the code he actually has 0 patrols in Vanilla.

> Also could we have a list of units and their hex values?  
I have to investigate quite a bit for these values, so maybe I'll do it this evening.

> I am halfway done with creating a small tool to create scripts.
I had something like this already in mind. Thanks for helping out!
It could take a bit until I find the time to implement this though.

**Comment by ByBurton** [comment] 2019-03-05 08:23
More examples:

[Scripts.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/2929899/Scripts.zip)

**Comment by PitchNeeded** [comment] 2019-03-05 10:01
> (Yes, Emir (with weapon purchasing) can have a bunch of additional European archers, but still he doesn't get anywhere near Nizar's numbers. And Emir's oil engineers are AIV-specific and can be used by Nizar as well.)

I do notice Emir is better now he can buy bows with his lookout towers manned, especially when enemy horse archer raids come to call at his castle (archers on lookout towers seem to be good against horse archers). 

As for boiling oil, like Richard who has the same problem, half the time the oil doesn't work at all when poured from the keep :( No fire at all created. This needs to be fixed I think.

>Richard. A few more archers than vanilla, but also pikemen and swordmen for wall defence.
Emir: A few Arabian swordsmen as wall defence?

Well I suppose this would be good against siege towers but none of the other AI use them as yet....(I suppose Snake uses ladders though)

> Sheriff ... Yeah. He needs an upgrade to the priority of defensive crossbowmen. Most games he'll only have 4-5 crossbowmen -total- defending his castle. He relies way too much on firethrowers who can be easily killed.

That's why I was thinking slingers for Sheriff, they would be good to support the crossbowmen in the towers.

> Saladin / Wazir: A few more arabian archers, very few slingers (maybe?) and a few more patrols. For Wazir even more patrols.

I think Saladin should have a few slingers on walls (as he is a character that already uses a wide variety of Arabian troops), but it might take away from Emir and Wazir's characters to use slingers as a troop type A few additional archers on each of their big towers would probably be better.

> Abbot: I hate this guy. Give him more patrols for his economy. He is a hamster after all.

He should I think also send a big group of monks to counterattack any enemy melee troops attacking his front walls.

**Comment by ByBurton** [comment] 2019-03-05 10:07
> (archers on lookout towers seem to be good against horse archers)

Everything on lookout towers is good. Those are overpowered.


> Well I suppose this would be good against siege towers but none of the other AI use them as yet....(I suppose Snake uses ladders though)

Wrong, this can be effective on all situations. If someone breaches the walls and gets into the castle, additional melee units are much more effective than ranged units.

**Comment by Lolasik011** [comment] 2019-03-05 11:18
@ByBurton  thank you for this program. You GOD!!!!

**Comment by ByBurton** [comment] 2019-03-05 11:54
@Lolasik011 Nope. No god here! Maybe a goddess though.
Also ... NOPE!
Just a programmer!

**Comment by Monsterfisch** [comment] 2019-03-05 17:35
looking great looking forward to messing around with all the new possibilities! 
I have to ask through since I am neither a god/godess or programmer ;) how do we add the scripts so they work in game? or is that something which would have to be implemented by showdown first?

**Comment by ByBurton** [comment] 2019-03-05 18:23
> looking great looking forward to messing around with all the new possibilities!
> I have to ask through since I am neither a god/godess or programmer ;) how do we add the scripts so they work in game? or is that something which would have to be implemented by showdown first?

I can tell you. You can not do anything yet. They won't work. @Sh0wdown will have to implement a way to use them at some point. We are working together on a project regarding this.

**Comment by Panbutt** [comment] 2019-03-05 18:40
That's very cool work, opens a lot of doorways :D.

Reporting a bug with the latest patch however. Emir will not hire European archers for defense when on Deathmatch (much gold little troopers) settings. This was a bug on Crusader (little gold much troops) settings as well but it only effected Arabian Archers.

**Comment by ByBurton** [comment] 2019-03-05 18:46
@Panbutt Sure that it does not just take a long time? Just wait a little longer.

**Comment by Heroesflorian** [comment] 2019-03-06 00:36
> > Abbot: I hate this guy. Give him more patrols for his economy. He is a hamster after all.
> 
> Judging from the code he actually has 0 patrols in Vanilla.

Hmm... I definitely remember him sending dozens of archers to protect his farmers and other workers, similar to how Saladin or others also do it. (And separate from his harassment monks who approach hostile buildings.) 

But possibly there is a distinction to be made here... patrols (patrolling quarries, various farms and other buildings pretty much independent from enemy activity) and "worker-protecting archers / ranged troops" (actively moving to wherever own workers were attacked by enemy troops or workers).

**Comment by Heroesflorian** [comment] 2019-03-06 00:46
Re melee troops on walls: Even without a wall breach, I guess they could sometimes be somewhat useful as distraction / meat shield as well. 
And (when patrolling like Rat's spearmen) have some value as "mobile" / non-stationary defensive troops that slightly increases the need for good timing for attacks and adds some dynamics to sieges. 
And of course, for wall breaches and/or siege towers / ladders / assassins / accessible walls, they provide big value to defenders. 
(And yes, e.g. walls lowered by mangonels or catapults to the point where they can be entered from the outside are less unlikely than you may think... already happened to (especially thick-walled) AI characters a number of times, even happened to me against the AI already, with just 1 Snake catapult firing at my thick front wall for about 10 seconds, to then rush onto it with dozens of spearmen, archers and slaves... ugh! :D)

**Comment by PitchNeeded** [comment] 2019-03-06 13:24
> That's very cool work, opens a lot of doorways :D.
> 
> Reporting a bug with the latest patch however. Emir will not hire European archers for defense when on Deathmatch (much gold little troopers) settings. This was a bug on Crusader (little gold much troops) settings as well but it only effected Arabian Archers.

Does it only happen on Deathmatch?

I noticed a while ago that Emir won't hire European archers even for defence if he is intending to attack an AI player or human player without a moat.

And yes on Crusader mode (little gold much troops), Emir starts with loads of horse archers instead of Arabian archers like Caliph, Wazir or Saladin (and I like this as it makes him different) but the problem is he doesn't seem to man his towers properly until those starting horse archers are killed :(

**Comment by Panbutt** [comment] 2019-03-06 23:42
> @Panbutt Sure that it does not just take a long time? Just wait a little longer.

Yeah nvm. I guess just a really weird bug with the custom AIVs i'm using. Tried it out on vanilla AIVs and its fine, switched over to mine and Emir seems to ignore the archer tokens. Probs just a corruption on my end or something.

RE Slingers for Sheriff: Considering Sheriff's units already deal -25% damage when he's in full swing, Slingers for him would be kinda useless. I would suggest instead Arabian Archers and braziers as Sheriff uses pitch so he'd get better usage out of them. Same deal with Caliph. The 5 tier negative fear factor on Slingers makes them nearly worthless.

Instead I'd say perhaps Saladin could use slingers? Slingers atm are the only unit Arab unit he doesn't use. And right now, Saladins castle defenses are a bit pitiful. Only 1 firethrower per spot and 3 archers per spot. They can be overwhelmed pretty easily. I think upping the count to 5 archers per spot and 2 firethrowers per spot while allowing him to use slingers defensively would help a lot.

**Comment by ByBurton** [comment] 2019-03-07 10:28
Slingers just does not suit the Sheriff though. Not at all. It is like giving the rat swordsmen, kind of.

**Comment by PitchNeeded** [comment] 2019-03-07 10:55
> RE Slingers for Sheriff: Considering Sheriff's units already deal -25% damage when his fear factor is in full swing, Slingers for him would be kinda useless. 

Does negative fear factor affects unit health or unit damage given....

Anyway, yes on reflection, for Sheriff and Wazir it might not be best to have slingers, but also for Caliph, they won't be as effective with his -5 fear factor, but I suppose if he was supposed to have singers then he should have them.

> And right now, Saladins castle defenses are a bit pitiful. Only 1 firethrower per spot and 3 archers per spot. They can be overwhelmed pretty easily. I think upping the count to 5 archers per spot

I think Saladin, Abbot, Emir and Wazir could do with more archers per spot, especially as they have big castles. I suggested 4 more archers per spot for each, apart from Emir who uses both types of archers, he should have 2 more European archers and 2 more Arabian archers per spot I think.

> Yeah nvm. I guess just a really weird bug with the custom AIVs i'm using. Tried it out on vanilla AIVs and its fine, switched over to mine and Emir seems to ignore the archer tokens. Probs just a corruption on my end or something.

There is still a problem with Emir manning his towers on Crusader mode (low gold, many troops) though as far as I am aware.

**Comment by ByBurton** [comment] 2019-03-07 11:51
> There is still a problem with Emir manning his towers on Crusader mode (low gold, many troops) though as far as I am aware.

This is a problem probably not limited to Emir. The additional starting troops might count towards the wall / total defence, which may prohibit recruiting additional units.

**Comment by Panbutt** [comment] 2019-03-07 20:02
> Does negative fear factor affects unit health or unit damage given....

It affects damage. A 'neutral' crossbowman can oneshot a neutral slave, but a -5 crossbowman will have to double tap a neutral slave. This sentence sounds odder than it should. Anyway, a -5 crossbowman leaves a slave on just a tiny sliver of HP after the first shot, result of -25% damage. I feel like thats why Wolf compliments his defensive crossbowmen with archers to compensate for the damage loss.

**Closed** 2019-08-19 11:36 UTC
Labels: discussion, enhancement
