### ISSUE TITLE
 Bug when choosing the Russian language in Launcher.

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#310] opened 2019-04-07 18:28 UTC
Bug when choosing the Russian language in Launcher.
![Bug](https://user-images.githubusercontent.com/41998977/55687982-1be01d80-597c-11e9-9383-1b4520c2d8c6.png)

**Comment by Lolasik011** [comment] 2019-04-07 18:35
@Sh0wdown 
For now, I'll play the English version.
If you have  will be time. Look here please...

**Comment by Sh0wdown** [comment] 2019-04-07 18:36
wtf I don't get that error with the russian version

**Comment by Lolasik011** [comment] 2019-04-07 18:37
@Sh0wdown 
hmm ... I  reinstall the game. And write to you ...

**Comment by Sh0wdown** [comment] 2019-04-07 18:39
Shouldn't be a problem with the game but the UCP.

**Comment by Sh0wdown** [comment] 2019-04-07 21:29
Could you try redownloading the UCP? Maybe the download was just corrupted.

**Comment by Lolasik011** [comment] 2019-04-07 21:34
@Sh0wdown ;(
[icp_error_dump.txt](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/3052054/icp_error_dump.txt)

**Comment by Sh0wdown** [comment] 2019-04-07 21:45
The problem is, I do not get that error so it is hard to debug for me.
Could you try this version?
https://www.dropbox.com/s/qs7g1eewghtw1vm/UnofficialCrusaderPatch-test.exe?dl=0

**Comment by Lolasik011** [comment] 2019-04-07 21:49
@Sh0wdown same :(

**Comment by Sh0wdown** [comment] 2019-04-07 21:58
Could you try this one
https://www.dropbox.com/s/sqnvjfr9cydaqzj/UnofficialCrusaderPatch-test2.exe?dl=0

**Comment by Lolasik011** [comment] 2019-04-07 22:15
@Sh0wdown 
There was not one Bug Not even the old Bugs! Thank you very much!

But I'm still testing with all the options.

**Comment by Sh0wdown** [comment] 2019-04-07 22:21
Weird. Could you try this as a last one:
https://www.dropbox.com/s/i06hsusm1koj5gb/UnofficialCrusaderPatch-test3.exe?dl=0

**Comment by Lolasik011** [comment] 2019-04-07 22:37
@Sh0wdown 
![Безымянный](https://user-images.githubusercontent.com/41998977/55690799-c9fcbf00-599e-11e9-88b2-67ff12a50b5d.png)

Only old errors .... New error does not appear ....

**Comment by Sh0wdown** [comment] 2019-04-07 22:50
Okay, thank you very much! Still weird why that error appeared though. Closing here...

**Closed by Sh0wdown** 2019-04-07 22:50 UTC
Labels: bug
