### ISSUE TITLE
AI Behaviour

### ISSUE THREAD

**Issue by cybercorpse** [Sh0wdown/UnofficialCrusaderPatch#8] opened 2018-11-05 09:22 UTC
Hi, Sh0wdown! Is it possible for you to edit some options of the AI's behavior, like his preferable troops, use of siege equipment, etc?

**Comment by Sh0wdown** [comment] 2018-11-05 09:46
I haven't looked into it, but I think it should be possible.

**Comment by ByBurton** [comment] 2018-11-05 09:58
@Sh0wdown If so, could you for example make the Rat build more apple farms?
Or fix stuff like Wolf not manning his towers / walls with Arabic Archers?

I am getting more and more hyped for this. To be honest, I am checking every 30 minutes since I heard about this for updates, and getting the latest ones asap.


I would love to donate some money, do you have a paypal or smthg.? I don't wanna do monthly stuff though...

Also.... at some point .... can you please buff my poor ratty? :( 
(After eeeeeverything else is done, so probably never... I know how programming works..)

**Comment by cybercorpse** [comment] 2018-11-05 10:05
> I haven't looked into it, but I think it should be possible.

Oh, it would be great. Our developers have not figured it out a long time ago, working on Stronghold Europe...

**Comment by ByBurton** [comment] 2018-11-05 10:22
> Oh, it would be great. Our developers have not figured it out a long time ago, working on Stronghold Europe...

I played a lot with your modification Stronghold Europe. 
I enjoyed especially the old soundtrack in Stronghold Crusader!

**Comment by PitchNeeded** [comment] 2018-11-08 21:36
> Hi, Sh0wdown! Is it possible for you to edit some options of the AI's behavior, like his preferable troops, use of siege equipment, etc?

Oh my goodness, it might actually be possible to make King Phillip have a proper siege force, with knights heading directly for the walls along with catapults and the spearmen and some archers to support!

**Comment by ByBurton** [comment] 2018-11-09 08:40
> Oh my goodness, it might actually be possible to make King Phillip have a proper siege force, with knights heading directly for the walls along with catapults and the spearmen and some archers to support!

Knights ... heading for walls .... does not sound promising to me...
I would rather have him build catapults for attacks, with a lot more spearmen..

**Comment by Flechador** [comment] 2018-11-09 22:35
> Well before he attacks you he sometimes says 'My knights will ride you down, charge!' so it would make sense for King Phillip to have at least a few knights in his main siege force to try and chop down the walls along with the spearmen before destroying the granary/marketplace etc inside the castle if they break through the walls!

I like that idea, because it would be convenient with Phillip. I mean his attacks currently are just bad Rat attacks without Archers.

**Comment by PitchNeeded** [comment] 2018-11-11 15:53
With all these amazing changes now being able to be made to the AI, would it be possible eventually to make a completely new AI lord for Stronghold Crusader. I will use my imagination now, and here is my plan for a future AI lord for Stronghold Crusader 😄 

AI lord: The Bandit Lord (or maybe even 'Robin Hood' as he took part in the Crusades according to the story) The two videos for the bandit attacks in Stronghold Crusader invasion scenarios could be used for him when he sends messages to the player. He is the one with the green hood.

Troop type: Archers, tunnelers and catapults

Tactics: Hundreds of tunnelers trained (he would be a a bit like the Abbot with tunnelers instead of monks!) who would fight rather than just dig tunnels, although some tunnels would be dug by him in sieges. He would also raid quarries/iron mines/farms with big groups of tunnelers, supported by some archers. Tunnelers are fast and surprisingly good in attack as this video shows https://www.youtube.com/watch?v=ndngWhyt7Ck Better than spearmen or monks! He would also use a lot of archers to defend farms/mines/quarries and also to support the tunnelers in sieges.

Economy: Apple farming, stone, iron, pitch, ale production, religion, quite a few fletchers, overall a good economy to afford big armies. No use of fear factor.

Castle: quite good, lots of archers on towers, ballistae on towers but no mangonels. Quite a few wooden traps and some pitch too as he is a cunning bandit lord!

**Comment by Lolasik011** [comment] 2018-11-13 15:03
Very good idea !

**Comment by PitchNeeded** [comment] 2018-11-13 18:46
Thanks! My proposed Lord Woolsack AI wouldn't be one of the absolute strongest AI's, but he could pose a threat with his lines of pikemen marching across the map!

Obviously if this AI was ever made, we should make it so you would have to have Stronghold 1 to be able to download this new AI.

**Comment by PitchNeeded** [comment] 2018-11-15 11:44
I don't know if this is possible to do, but it would be good to be able to improve AI siege tactics in terms of which units advance first. A good example would be improving Sultan's tactics. It would be better if Sultan grouped his Arabian archers and Arabian swordsmen together before a siege, advancing his Arabian swordsman first and then the Arabian archers sometime later so they can actually distract the enemy when the Arabian swordsman are advancing!

Another example is Wolf's crossbowmen, who should advance ideally at the same time as the pikemen and swordsmen!

**Comment by FixStronghold** [comment] 2018-11-16 12:47
Great work so far, I am guessing a few things will remain broken forever, but here are a few observations I made about the way the AI performs its attacks that is close to being buggy or is at least lazy coding and I believe no one has mentioned yet:

- The AI is sluggish. It sometimes takes the AI multiple seconds to realize that the wall has been breached for example or issue new commands to troops that have destroyed a building. My guess is that there is some artificial APM limit for the AI? Personally I would like to see it removed, since the AI is weak enough as it is. 

- The melee troops of the AI attack walls around the keep and that is it (until it is breached). You or the AI being attacked can have vital buildings outside of your walls and the AI during an attack will simply ignore it. It also gets more stupid than that if you for example have a moat blocking part of the wall except keeping a small part open or blocking part of the wall with other buildings. The AI will then only send groups that are able to attack the wall at once at any time. Maybe this could be fixed by adding more control groups for the AI to work with and changing building prioritization.

- I am sure we all know this but moats are just broken. The only unit that can remove moats reliably during an attack are pikemen. Maybe at least give all infantry units in the game the option to dig-out moats.

- The AI does not use shields, which are needed to clear archers from towers. 

- The AI does not use siege equipment effectively and not enough. I would have thought the strongest AI should try to use more than 6 catapults during an attack and wait for these to deal damage. Usually the interval between sending troops and giving the siege equipment time to deal damage is too short.

**Comment by PitchNeeded** [comment] 2018-11-16 16:37
> You or the AI being attacked can have vital buildings outside of your walls and the AI during an attack will simply ignore it. 

That's more for any raiding AI troops though to target. 

> I am sure we all know this but moats are just broken. The only unit that can remove moats reliably during an attack are pikemen. Maybe at least give all infantry units in the game the option to dig-out moats.

Arabian archers at least should be able to dig moats, that would allow Sultan to be finally be able to dig up enemy moats :smile:

**Comment by Flechador** [comment] 2018-11-16 18:51
> Maybe at least give all infantry units in the game the option to dig-out moats.

Maybe it's possible to change that all units can dig-out moats but it would look "bugged". Because the other units dont have animations for dig-out moats.

**Comment by FixStronghold** [comment] 2018-11-18 02:10
> I don't think it's a big issue, outside buildings are more for any raiding AI troops though to target, and anyway AI catapults or fire ballistae often manage to destroy some buildings outside the wall anyway.

Sorry I meant that the AI only attacks in waves that are large enough to attack the walls, which severely limits the strength of an AI when it has more troops. My suggestion was meant as part of a "fix" to have it also target other buildings or digging-up the moat. 

You can test it for yourself, do the following: Play against Sultan, build a complete wall around your keep and cover the wall on the outside with flower gardens (or any other buildings even towers work). Depending on how much space you leave open will determine the size of the waves. I had a Saladin with a moat in front and his walls for the most part covered in bakeries or other buildings. He could defend himself effectively against multiple AIs attacking with 400 troops or more, because they would only ever send 10 troops at once. I guess part of the problem is also that the AI is completely inept at using siege equipment.

**Comment by Panbutt** [comment] 2018-11-18 07:54
Yeah. Melee soldiers also never, ever target gatehouses unless they are assassins. With the grand majority of the AI castles, destroying a single gatehouse can create a breach yet the AI doesn't seem to prioritize targeting them.

**Comment by PitchNeeded** [comment] 2018-11-18 14:31
> Yeah. Melee soldiers also rarely, if not ever, target gatehouses unless they are assassins. With the grand majority of the AI castles, destroying a single gatehouse can create a breach yet the AI doesn't seem to prioritize targeting them.

Although Richard and Pig tend to send rams to gatehouses, and Marshall, Frederick and Phillip may attack them with their knight raids if they have already destroyed outside buildings in the area and there is no other target nearby.

Sometimes it might not be be wise for an AI to attack a gatehouse, some AI's (like Richard and Emir) have boiling oil engineers on them whereas their walls are less defended. Also I have noticed that Wazir has small areas midway between the points of some of his star shaped vanilla castles where his archers can't fire at the wall chopping troops and the AI often manages to break through here.

> Depending on how much space you leave open will determine the size of the waves. I had a Saladin with a moat in front and his walls for the most part covered in bakeries or other buildings. He could defend himself effectively against multiple AIs attacking with 400 troops or more, because they would only ever send 10 troops at once. I guess part of the problem is also that the AI is completely inept at using siege equipment.

I think the AI is good enough at using siege equipment, they aim for the towers first which is a good enough decision, as if they manage to destroy towers, particularly with AI's like Caliph who only have weak towers then the enemy firepower is reduced. 

However the point about the 10 troops at once is something that needs to be improved definitely. I assume Richard, Pig, Sheriff and Wolf are slightly more successful at sieging Saladin's castle as they bring decent moat digging troops so can send more troops at once.

**Comment by FixStronghold** [comment] 2018-11-18 15:37
> Although Richard and Pig tend to send rams to gatehouses, and Marshall, Frederick and Phillip may attack them with their knight raids if they have already destroyed outside buildings in the area and there is no other target nearby.

Just to make this clear, we are not saying that the AI should target gatehouses or towers instead of walls, but additionally. There is only so many units that can attack the wall at any one time, which can be very restrictive if the wall is not reachable or the stronghold is small. 

> I think the AI is good enough at using siege equipment, they aim for the towers first which is a good enough decision, as if they manage to destroy towers, particularly with AI's like Caliph who only have weak towers then the enemy firepower is reduced.

Well I agree with what you said, but there are two big issues: Often the AI moves their catapults too close or builds them up too close and gets them destroyed, and secondly they often do not shoot for long enough to really destroy anything. I should maybe mention that there are two types of catapults, ones used for attack and others that are built to shoot at close enemies. I am only talking about the latter, the ones to attack enemies close-by seem to work okayish, although they are also often pushed into archer range. 

> However the point about the 10 troops at once is something that needs to be improved definitely. I assume Richard, Pig, Sheriff and Wolf are slightly more successful at sieging Saladin's castle as they bring decent moat digging troops so can send more troops at once.

Well you have a point and you would think that should be the case..., but in my game with Saladin it was Friedrich and Wolf. Anyway I ran another test with moats by building a complete moat around my keep to see what the problem is. So turns out there is indeed some coding to remove moats, but it is less than ideal and does not work in most scenarios. Both Pig and Wolf will send exactly 1 wave of about 10 units to remove a moat and that is it. Both Wolf and Pig still had plenty of units to send to remove the moat in each attack but instead just stood idly around..., again you can test this yourself.

**Comment by Sh0wdown** [comment] 2019-04-07 17:17
Possible with AIC edits.

**Closed by Sh0wdown** 2019-04-07 17:17 UTC
Labels: question

**Comment by saberzokabo** [comment] 2020-11-05 17:22
eh,can i change an AI units? & how?

**Comment by GRhin** [comment] 2020-11-06 03:41
It's all in the aic files https://sh0wdown.github.io/UnofficialCrusaderPatch/aic/overview.html
